# Generated by Django 5.2.4 on 2025-07-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "할 일", "verbose_name_plural": "할 일 목록"},
        ),
    ]
