# Generated by Django 5.2.4 on 2025-07-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="todo/%Y/%m/%d", verbose_name="이미지"
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="todo/%Y/%m/%d/thumbnail",
                verbose_name="썸네일",
            ),
        ),
    ]
