# Generated by Django 5.2.4 on 2025-08-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="닉네임"
            ),
        ),
    ]
