# Generated by Django 5.2.4 on 2025-08-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="닉네임",
            ),
        ),
    ]
